
image_topic: "/mtuav/stereo_down0/image_raw"
pl_feature_cfg:
        # H: 480 # Input image height
        # W: 752 # Input image width
        H: 800 #317
        W: 1280 #474
        min_cnt: 150

        extract_method: "sp-sold2"    # supported: [superpoint]
        sp-sold2:
                ckpt_path: "/home/nnplvio_ws/src/nn-pl-vio/feature_tracker/scripts/utils_pl/pretrained_models/sp-sold2.tar"
                model_name: "superpoint_simple"
                model_architecture: "simple"
                # Backbone related config
                backbone: "superpoint"
                backbone_cfg:
                input_channel: 1 # Use RGB images or grayscale images.
                depth: 4
                num_stacks: 2
                num_blocks: 1
                num_classes: 5
                # Junction decoder related config
                junction_decoder: "superpoint_decoder"
                junc_decoder_cfg:
                # Heatmap decoder related config
                heatmap_decoder: "pixel_shuffle"
                heatmap_decoder_cfg:
                # Descriptor decoder related config
                descriptor_decoder: "superpoint_descriptor"
                descriptor_decoder_cfg:
                # Shared configurations
                grid_size: 8
                pad_size: 1
                keep_border_valid: True
                # Threshold of junction detection
                detection_thresh: 0.0153846 # 1/65
                # Threshold of heatmap detection
                prob_thresh: 0.5
                ########### point extraction ##########
                conf_thresh: 0.005 #0.1 # Detector confidence threshold
                nms_dist: 4
                nn_thresh: 0.7
                border_remove: 4 # Remove points this close to the border.
                # H: 480
                # W: 752
                H: 800 #317
                W: 1280 #474
                ########### line extraction ##########
                num_samples: 5
                min_dist_pts: 8
                line_score: false
                sampling: "regular"
                topk: 300
                line_detector_cfg:
                        detect_thresh: 0.3  # depending on your images, you might need to tune this parameter
                        num_samples: 30
                        sampling_method: "bilinear"
                        inlier_thresh: 0.9
                        use_candidate_suppression: False
                        nms_dist_tolerance: 3.
                        use_heatmap_refinement: True
                        heatmap_refine_cfg: 
                                mode: "global"
                                ratio: 0.2
                                valid_thresh: 0.001
                                num_blocks: 20
                                overlap_ratio: 0.5
       
point_feature_cfg:
        H: 800 # Input image height
        W: 1280 # Input image width
        min_cnt: 150
        match_method: "nnm"       # supported: [nnm，superglue]
        nnm:
                max_length: 5  # Maximum length of point tracks
                nn_thresh: 0.7 # Descriptor matching threshold
line_feature_cfg:
        H: 800 # Input image height
        W: 1280 # Input image width
        min_cnt: 60
        num_samples: 5
        match_method: "wunsch"
        wunsch:
                cross_check: True
                top_k_candidates: 10
                line_score: false

camera_cfg:
        model_type: PINHOLE
        camera_name: camera
        image_width: 1280
        image_height: 800
        distortion_parameters:
                k1: 8.4479988187990004e-02
                k2: -8.2715949932212887e-02
                p1: 9.2522968667606312e+02
                p2: 3.9723800223006913e+02
        projection_parameters:
                fx: 9.2544856424722730e+02
                fy: 6.1276180358215265e+02
                cx: 3.630e+02
                cy: 2.481e+02
