
image_topic: "/mtuav/stereo_down0/image_raw"
point_feature_cfg:
        H: 800 # Input image height
        W: 1280 # Input image width
        min_cnt: 150

        extract_method: "superpoint"    # supported: [superpoint]
        superpoint:
                weights_path: '/home/nnplvio_ws/src/nn-pl-vio/feature_tracker/scripts/utils_point/superpoint/superpoint_v1.pth'
                nms_dist: 4    # Non Maximum Suppression (NMS) distance
                conf_thresh: 0.015 # Detector confidence threshold
                nn_thresh: 0.7 # Descriptor matching threshold 
                cuda: true # Use cuda GPU to speed up network processing speed
       
        match_method: "nnm"       # supported: [nnm，superglue]
        nnm:
                max_length: 5  # Maximum length of point tracks
                nn_thresh: 0.7 # Descriptor matching threshold
        superglue:
                sinkhorn_iterations: 20
                match_threshold: 0.2
                weight_path: "/home/nnplvio_ws/src/nn-pl-vio/feature_tracker/scripts/utils_point/superglue/superglue_outdoor.pth"
line_feature_cfg:
        H: 800 # Input image height
        W: 1280 # Input image width
        min_cnt: 100
        num_samples: 5
        extract_method: "sold2"
        sold2:
                min_dist_pts: 8
                line_score: false
                sampling: "regular"
        match_method: "wunsch"
        wunsch:
                cross_check: True
                top_k_candidates: 10
                line_score: false
        
#camera calibration 
camera_cfg:
        model_type: PINHOLE
        camera_name: camera
        image_height: 1280
        image_width: 800
        distortion_parameters:
                k1: 8.4479988187990004e-02
                k2: -8.2715949932212887e-02
                p1: 9.2522968667606312e+02
                p2: 3.9723800223006913e+02
        projection_parameters:
                fx: 9.2544856424722730e+02
                fy: 6.1276180358215265e+02
                cx: 3.630e+02
                cy: 2.481e+02

